# Generated by Django 2.1.7 on 2019-03-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libbackend', '0002_auto_20190127_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='libbackend.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='libbackend.Genre'),
        ),
    ]
