# Generated by Django 2.2 on 2019-04-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libbackend', '0004_auto_20190406_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_image', to='libbackend.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
